---
name: Term-Terminfo
version: 0.04
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: access the F<terminfo> database
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
  Module::Build::Compat: 0
provides:
  Term::Terminfo:
    file: lib/Term/Terminfo.pm
    version: 0.04
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
